---
version: "3"

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

  api:
    image: librarian:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres